### PR TITLE
travis to check the build process

### PR DESCRIPTION
**Pull request by isabelrios**

### CODE REVIEW

**Comment by isabelrios** [comment]
@mcav r? this is the first approach I have thought of. Not sure if this works, would need the .travis.yml file in the repo to check it or maybe there is other way but do not know how.
Thanks

**Comment by isabelrios** [comment]
@mcav did you have a chance to look at it? if it does not look good I can try other solutions but I think we would need to add travis checks to the repo better sooner than later. Thanks!

**Review by mcav — APPROVED** [review]
Sorry, I forgot there was a PR! This seems like a good start. I don't know if the gradle linter will provide any useful information, but it seems reasonable to start off with so that we have something to execute.

**Comment by isabelrios** [comment]
@mcav thanks! Seems I can not merge the PR, I could not test that travis will work, but once it is added I will take care of it

**Comment by mcav** [comment]
I sent you an invite to the org that should let you merge; I also merged this one for now.

**Pull request merged**
